version: 2
jobs:
  build:
    working_directory: /home/development/go/src/github.com/goMLLibrary
    docker:
      - image: kurama554101/go-ml-library:0.1
    steps:
      - checkout # checkout goMLLibrary into working_directory
      - run:
          name: Execute Setup
          command: |
            pwd
            ls -l
            ls -l install
            bash install/setup_container.sh
            source ~/.bash_profile
            echo "end setup"
          working_directory: /home/development/go/src/github.com/goMLLibrary
